db.movies.insertOne({{ "_id" : ObjectId("61d70982950fd276e05fec1f"), "Title" : "Evolution", "Year" : "2021", "Description" : "Episodes trace three generations of a family, from a surreal memory of World War II to modern day Berlin.", "Genre" : { "Name" : "Drama", "Description" : "The drama genre is defined by conflict and often looks to reality rather than sensationalism. Emotions and intense situations are the focus." }, "Director" : { "Name" : "Kornél Mundruczó", "Bio" : "Kornél Mundruczó is a Hungarian film and theatre director. He has directed 18 short and feature films between 1998 and 2020.", "Birth" : "1975", "Death" : "NULL" }, "ImagePath" : "Evolution.png", "Featured" : false }})

db.movies.insertOne({ "_id" : ObjectId("61d70982950fd276e05fec20"), "Title" : "Edward Scissorhands", "Year" : "1990", "Description" : "An artificial man, who was incompletely constructed and has scissors for hands, leads a solitary life. Then one day, a suburban lady meets him and introduces him to her world.", "Genre" : { "Name" : "Fantasy", "Description" : "The fantasy genre is defined by both circumstance and setting inside a fictional universe with an unrealistic set of natural laws." }, "Director" : { "Name" : "Tim Burton", "Bio" : "is an American film director, producer, writer and artist. He is known for his gothic fantasy and horror films.", "Birth" : "1958", "Death" : "NULL" }, "ImagePath" : "edward-scissorhands.png", "Featured" : true })

db.movies.insertOne({ "_id" : ObjectId("61d70982950fd276e05fec21"), "Title" : "Titanic", "Year" : "1997", "Description" : "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.", "Genre" : { "Name" : "Romance", "Description" : "The romance genre is defined by intimate relationships. Sometimes these movies can have a darker twist, but the idea is to lean on the natural conflict derived from the pursuit of intimacy and love." }, "Director" : { "Name" : "James Cameron", "Bio" : "is a Canadian filmmaker. Best known for making science fiction and epic films, he first gained recognition for directing The Terminator (1984).", "Birth" : "1954", "Death" : "NULL" }, "ImagePath" : "Titanic.png", "Featured" : true })

db.movies.insertOne({ "_id" : ObjectId("61d70982950fd276e05fec22"), "Title" : "Tenet", "Year" : "2020", "Description" : "Armed with only one word, Tenet, and fighting for the survival of the entire world.", "Genre" : { "Name" : "Sci-Fi", "Description" : "The Science fiction needs to shine a light on the world the way it could be or the way we think it might happen. It takes us on adventures into the near and distant future." }, "Director" : { "Name" : "Christopher Nolan", "Bio" : "Christopher Nolan is a British-American film director, producer, and screenwriter", "Birth" : "1970", "Death" : "NULL" }, "ImagePath" : "tenet.png", "Featured" : true }) 

db.movies.insertOne({ "_id" : ObjectId("61d70982950fd276e05fec23"), "Title" : "Inception", "Year" : "2010", "Description" : "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom.", "Genre" : { "Name" : "Sci-Fi", "Description" : "The Science fiction needs to shine a light on the world the way it could be or the way we think it might happen. It takes us on adventures into the near and distant future." }, "Director" : { "Name" : "Christopher Nolan", "Bio" : "Christopher Nolan is a British-American film director, producer, and screenwriter", "Birth" : "1970", "Death" : "NULL" }, "ImagePath" : "inception.png", "Featured" : true })

db.movies.insertOne({ "_id" : ObjectId("61d70982950fd276e05fec24"), "Title" : "Barton Flink", "Year" : "1991", "Description" : "A renowned New York playwright is enticed to California to write for the movies and discovers the hellish truth of Hollywood.", "Genre" : { "Name" : "Comedy", "Description" : "The comedy is defined by events that are intended to make someone laugh, no matter if the story is macabre, droll, or zany." }, "Director" : { "Name" : "Joel Coen", "Bio" : "Joel Coen is a director, producer and writer.", "Birth" : "1954", "Death" : "NULL" }, "ImagePath" : "Barton-Flink.png", "Featured" : true })

db.movies.insertOne({ "_id" : ObjectId("61d70982950fd276e05fec25"),  "Title" : "127 Hours", "Year" : "2010", "Description" : "A mountain climber becomes trapped under a boulder while canyoneering alone near Moab, Utah and resorts to desperate measures in order to survive.", "Genre" : { "Name" : "Biography", "Description" : "This genre follows a real life incidents or someone’s biography." }, "Director" : { "Name" : "Danny Boyle", "Bio" : "Danny Boyle is a British director and producer.", "Birth" : "1956", "Death" : "NULL" }, "ImagePath" : "127-hrs.png", "Featured" : true })

db.movies.insertOne({"_id" : ObjectId("61d70982950fd276e05fec26"), "Title" : "The Godfather", "Year" : "1972", "Description" : "The Godfather follows Vito Corleone Don of the Corleone family as he passes the mantel to his son Michael.", "Genre" : { "Name" : "Crime", "Description" : "The crime genre deals with both sides of the criminal justice system but does not focus on legislative matters or civil suits and legal actions." }, "Director" : { "Name" : "Francis Ford Coppola", "Bio" : "Francis Ford Coppola is an American film director, producer, and screenwriter. He was a central figure in the New Hollywood filmmaking movement of the 1960s and 1970s..", "Birth" : "1939", "Death" : "NULL" }, "ImagePath" : "The Godfather.png", "Featured" : true })

db.movies.insertOne({ "_id" : ObjectId("61d70982950fd276e05fec27"), "Title" : "The Rainmaker", "Year" : "1997", "Description" : "Rudy Baylor is a young attorney out to make a difference in the justice system. He is also the only hope of an elderly couple after their corrupt insurance company refuses to pay out a claim that could save their child's life.", "Genre" : { "Name" : "Crime", "Description" : "The crime genre deals with both sides of the criminal justice system but does not focus on legislative matters or civil suits and legal actions." }, "Director" : { "Name" : "Francis Ford Coppola", "Bio" : "Francis Ford Coppola is an American film director, producer, and screenwriter. He was a central figure in the New Hollywood filmmaking movement of the 1960s and 1970s..", "Birth" : "1939", "Death" : "NULL" }, "ImagePath" : "The Rainmaker.png", "Featured" : true  })

db.movies.insertOne({ "_id" : ObjectId("61d70982950fd276e05fec28"), "Title" : "Dracula", "Year" : "1992", "Description" : "The centuries old vampire Count Dracula comes to England to seduce his barrister Jonathan Harker's fiancée Mina Murray and inflict havoc in the foreign land.", "Genre" : { "Name" : "Horror", "Description" : "The horror genre is centered upon depicting terrifying or macabre events for the sake of entertainment." }, "Director" : { "Name" : "Francis Ford Coppola", "Bio" : "Francis Ford Coppola is an American film director, producer, and screenwriter. He was a central figure in the New Hollywood filmmaking movement of the 1960s and 1970s..", "Birth" : "1939", "Death" : "NULL" }, "ImagePath" : "Dracula.png", "Featured" : true  })
